---
# tasks file for nginx
- name: install httpd packages
  yum:
    name: nginx
    state: latest
  with_items: "{{httpd_packages}}"
  #notify: restart apache service

# - name: copy nginx.conf
#   template:
#     src: templates/nginx.conf.j2
#     dest: /etc/nginx/nginx.conf
#     mode: 0644
  #otify: restart nginx service

- name: install lists of packages
  yum:
    name:
      - postgresql
      - postgresql-server
      - git 
      - nodejs
    state: installed

- name: copy index.html
  template:
     src: templates/index.html.j2
     dest: /var/www/html/index.html
     
# - name: nginx service started
#   service:
#     name: nginx
#     state: started
#     enabled: yes

- name: certbotをインストール
  yum:
    name: certbot
    state: latest

- name: 証明書を取得
  command: certbot certonly --standalone -d tdsdys-wiki.com -w /var/www/html --email tadainfra@gmail.com --agree-tos --keep-until-expiring --non-interactive

- name: 証明書の自動更新設定
  cron:
    name: certbot
    cron_file: certbot
    user: root
    special_time: daily
    job: sh -c 'certbot renew && /usr/sbin/service nginx reload' >> /var/log/certbot/cron.log
