---
- hosts: localhost
  tasks:
  - name: create directory
    file:
        path: /Users/hoge/sandbox-codes/ansible-sandbox/ch2/tmp
        state: directory
        owner: sadayoshitada
        mode: 0755
  - name: copy file
    copy:
        src: /etc/hosts
        dest: /Users/hoge/sandbox-codes/ansible-sandbox/ch2/tmp
        owner: sadayoshitada
        mode: 0644
