apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-priority-class-row-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19-alpine
          resources:
            requests:
              memory: "500Mi"
          ports:
            - containerPort: 80