name: build-and-test

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.10
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWOR: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          which migrate
          cd go-sandbox/simplebank/
      - name: Run migrations
        run: make migrateup
      - name: Test
        run: make test